#Creates the services.
curl -S -s -i -X POST --url http://api-gateway:8001/services --data "name=chat-service" --data-urlencode "url=http://129.194.69.134:12085/chat"
curl -S -s -i -X POST --url http://api-gateway:8001/services --data "name=facebook-service" --data-urlencode "url=http://129.194.69.134:12084/facebook"
curl -S -s -i -X POST --url http://api-gateway:8001/services --data "name=filtering-service" --data-urlencode "url=http://129.194.69.134:12083/filtering"
curl -S -s -i -X POST --url http://api-gateway:8001/services --data "name=insta-service" --data-urlencode "url=http://129.194.69.134:12082/insta"
curl -S -s -i -X POST --url http://api-gateway:8001/services --data "name=profile-service" --data-urlencode "url=http://129.194.69.134:12086/profile"
curl -S -s -i -X POST --url http://api-gateway:8001/services --data "name=publication-service" --data-urlencode "url=http://129.194.69.134:12081/publication"
curl -S -s -i -X POST --url http://api-gateway:8001/services --data "name=twitter-service" --data-urlencode "url=http://129.194.69.134:12080/twitter"
#Creates the routes
curl -S -s -i -X POST  --url http://api-gateway:8001/services/chat-service/routes --data-urlencode "paths[]=/api/v1/chat" 
curl -S -s -i -X POST  --url http://api-gateway:8001/services/facebook-service/routes   --data-urlencode "paths[]=/api/v1/facebook"
curl -S -s -i -X POST  --url http://api-gateway:8001/services/filtering-service/routes   --data-urlencode "paths[]=/api/v1/filtering"  
curl -S -s -i -X POST  --url http://api-gateway:8001/services/insta-service/routes    --data-urlencode "paths[]=/api/v1/insta" 
curl -S -s -i -X POST  --url http://api-gateway:8001/services/profile-service/routes   --data-urlencode "paths[]=/api/v1/profile" 
curl -S -s -i -X POST  --url http://api-gateway:8001/services/publication-service/routes   --data-urlencode "paths[]=/api/v1/publication" 
curl -S -s -i -X POST  --url http://api-gateway:8001/services/twitter-service/routes   --data-urlencode "paths[]=/api/v1/twitter" 
#Enable the Open ID Plugin
#curl -S -s -i -X POST  --url http://api-gateway:8001/plugins --data "name=jwt" --data "enabled=true"
#curl -S -s -i -X POST  --url http://api-gateway:8001/consumers  --data "username=api-sso-proxied"   --data "custom_id=api-sso-proxied"
#curl -S -s -i -X POST  --url http://api-gateway:8001/consumers/api-sso-proxied/jwt   -F "algorithm=RS256"  -F "rsa_public_key=@/tmp/keycloak_rsa_provider-key-pub.pem" -F "key=https://localhost/auth/realms/apigw"
#curl -S -s -i -X POST  --url http://api-gateway:8001/consumers  --data "username=api-sso-not-proxied"   --data "custom_id=api-sso-not-proxied"
#curl -S -s -i -X POST  --url http://api-gateway:8001/consumers/api-sso-not-proxied/jwt   -F "algorithm=RS256"  -F "rsa_public_key=@/tmp/keycloak_rsa_provider-key-pub.pem" -F "key=http://iam:8080/auth/realms/apigw"
