INSERT INTO ingredients (id, name, unit) VALUES (1, 'tomato', 'kg')
INSERT INTO ingredients (id, name, unit) VALUES (2, 'milk', 'l')
INSERT INTO ingredients (id, name, unit) VALUES (3, 'sugar', 'g')
INSERT INTO ingredients (id, name, unit) VALUES (4, 'chicken', 'g')
INSERT INTO ingredients (id, name, unit) VALUES (5, 'avocado', 'unit')