language: java
service: docker
addons:
  sonarcloud:
    organization: pinfo-2020
    token:
      secure: f3ecafb44f260a694a8b6dc1b4b7b5be231fd2ca
script:
- mvn -X clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-3
  
