language: java
env:
- NODE_VERSION="12.15.0"
- SERVER_IP_ADDRESS=129.194.69.134
services:
- docker
addons:
  sonarcloud:
    organization: pinfo-2020
    token:
      secure: MVpHYotI+Kn9c492kURlipq8lqeuQ8dRxsAIaUUtouTr6IdAZAAXHSFn9zQ2pEk5J/PZZaRa9lmCBexpL47XYjzEnkealoyLtuIyK2vP6e7BFFvRp3wsdaeVTpQl3VRYsYyTiGXXCPVmmwxn8h3uUutHzrn89QvIkMHPzMc0VjOSv2+B9i/6EFg1BiKE0iTkllPYC06+4LIQ14HJkzhgl9DN3dSACQChA7SAisD/T2eRNpinfJP/k+hRo4I2eB+6G6JjktHre4/OcXX+OEIA6xExQjULCiijzhrUVYHhcTmoMo5EmrBPuKool8If6tTR+Gh7Gt2A7xGS9BslSmEIhpZmil4QKjbLrgOHqHV7zCVgeXCVla42S3Ge9EMdpskHtGMeGpEZ4wb5FwdrZKGJ0SX0RhbrrW+E9k3tQxNu4ErSXlN8urXBEWqf91bpnR5dXWbrw1ZTbVgOf0W7rduoGV/L6NJrmWyauegSLYFQbfZ5klbDOmI3IHI4jIo/uN9jsHpPags/6GGlhDWbI8f1yRqAGwtIZlP0X+DG41N7h13xlvJH8IFi307cUzCINNxv+xzu0Owi3yWMurpFYqZvP6pDYP/RrOJEYE7/yhd/vfiZ868CB1AFbXiQrraMqB1OZs7rbJ5qxvWHTt+f7nlCT4kKnRyDZJ+FxZRz0GzImcs=
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- mvn test
- mvn sonar:sonar -Dsonar.projectKey=PInfo-2020_PInfo-3 -Dsonar.organization=pinfo-2020
  -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=f719087dabb0280c1176fb6cc0be6d6b061709e6
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.test.skip=true -Ppackage-docker-image
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker tag unige/api-gateway kernel3/api-gateway:latest
- docker push kernel3/api-gateway:latest
- docker tag unige/regulatory-service kernel3/regulatory-service:latest
- docker push kernel3/regulatory-service:latest
- docker tag unige/valuation-service kernel3/valuation-service:latest
- docker push kernel3/valuation-service:latest
- docker tag unige/instrument-service kernel3/instrument-service:latest
- docker push kernel3/instrument-service:latest
- docker tag unige/counterparty-service kernel3/counterparty-service:latest
- docker push kernel3/counterparty-service:latest
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key aminman7@129.194.69.134 pwd
