--drop table itemCart if exists;
--create table itemCart (
--    itemCartID integer not null,
--    userID integer not null,
--    ingredientID integer not null,
--    quantity integer not null,
--    primary key (itemCartID)
--);
--DROP sequence if EXISTS ITEMCART_SEQ;
--INSERT INTO ITEMCART (userID, ingredientID, quantity) VALUES (1, 1, 2);
--INSERT INTO ITEMCART (userID, ingredientID, quantity) VALUES (2, 4, 2);
--INSERT INTO ITEMCART (userID, ingredientID, quantity) VALUES (3, 4, 2);