version: "3.5"

services:

  #Zookeeper service provides distributed configuration management to Kafka
  zookeeper:
    image: zookeeper:3.4.9
    container_name: zookeeper 
    hostname: zookeeper
    networks:
      - backend-network
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./target/zk-single-kafka-single/zoo1/data:/data
      - ./target/zk-single-kafka-single/zoo1/datalog:/datalog

#   kafka is the messaging backbone of the micro-service architecture. The objective is avoid point 2 point connections.
  kafka:
    image: confluentinc/cp-kafka:5.3.3
    container_name: kafka 
    hostname: kafka
    networks:
      - backend-network    
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - ./target/zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  shopping-database:
    image: postgres:10
    container_name: dige/shopping-database
    hostname: dige/shopping-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: sho
      POSTGRES_PASSWORD: sho
      POSTGRES_DB: sho
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sho", "-d", "sho"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-cpty:/var/lib/postgresql/data
      - ./test-data/shopping.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    stdin_open: true
    tty: true

  #The counterparty service provides counterparty data, it is also the single version of truth for these data
  shopping-service:
    container_name: shopping-service  
    image: dige/shopping-service:latest
    hostname: shopping-service
    environment:
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_CONNECTION_DASH_URL: "jdbc:postgresql://shopping-database:5432/shopping"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_USER_DASH_NAME: 'pro'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_PASSWORD: 'pro'
      THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST: "kafka"
      THORNTAIL_KAFKA_DASH_CONFIGURATION_PORT: "9092"
    networks:
      - backend-network 
    ports:
      - "12085:28080"
    depends_on:
       - kafka
#################################################################################################
#												#
#################################################################################################


  ingredients-database:
    image: postgres:10
    container_name: dige/ingredients-database
    hostname: dige/ingredients-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: ing
      POSTGRES_PASSWORD: ing
      POSTGRES_DB: ing
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ing", "-d", "ing"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-cpty:/var/lib/postgresql/data
      - ./test-data/ingredients.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    stdin_open: true
    tty: true

  #The counterparty service provides counterparty data, it is also the single version of truth for these data
  ingredients-service:
    container_name: ingredients-service  
    image: dige/ingredients-service:latest
    hostname: ingredients-service
    environment:
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_CONNECTION_DASH_URL: "jdbc:postgresql://ingredients-database:5432/ingredients"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_USER_DASH_NAME: 'ing'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_PASSWORD: 'ing'
      THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST: "kafka"
      THORNTAIL_KAFKA_DASH_CONFIGURATION_PORT: "9092"
    networks:
      - backend-network 
    ports:
      - "12084:28080"
    depends_on:
       - kafka

#################################################################################################
#												#
#################################################################################################


  profile-database:
    image: postgres:10
    container_name: dige/profile-database
    hostname: dige/profile-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: pro
      POSTGRES_PASSWORD: pro
      POSTGRES_DB: pro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pro", "-d", "pro"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-cpty:/var/lib/postgresql/data
      - ./test-data/profile.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    stdin_open: true
    tty: true

  #The counterparty service provides counterparty data, it is also the single version of truth for these data
  ingredients-service:
    container_name: profile-service  
    image: dige/profile-service:latest
    hostname: profile-service
    environment:
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_CONNECTION_DASH_URL: "jdbc:postgresql://profile-database:5432/profile"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_USER_DASH_NAME: 'pro'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_PASSWORD: 'pro'
      THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST: "kafka"
      THORNTAIL_KAFKA_DASH_CONFIGURATION_PORT: "9092"
    networks:
      - backend-network 
    ports:
      - "12083:28080"
    depends_on:
       - kafka

#################################################################################################
#												#
#################################################################################################


  recipes-database:
    image: postgres:10
    container_name: dige/recipes-database
    hostname: dige/recipes-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: rec
      POSTGRES_PASSWORD: rec
      POSTGRES_DB: rec
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "rec", "-d", "rec"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-cpty:/var/lib/postgresql/data
      - ./test-data/recipes.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    stdin_open: true
    tty: true

  #The counterparty service provides counterparty data, it is also the single version of truth for these data
  recipes-service:
    container_name: recipes-service  
    image: dige/recipes-service:latest
    hostname: recipes-service
    environment:
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_CONNECTION_DASH_URL: "jdbc:postgresql://recipes-database:5432/recipes"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_USER_DASH_NAME: 'rec'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_COUNTERPARTYDS_PASSWORD: 'rec'
      THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST: "kafka"
      THORNTAIL_KAFKA_DASH_CONFIGURATION_PORT: "9092"
    networks:
      - backend-network 
    ports:
      - "12082:28080"
    depends_on:
       - kafka

volumes:
   pgdata-cpty:
   pgdata-inst:
  

networks:
  backend-network:
    driver: bridge
