apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservices.fullname" . }}-web-ui-config
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "microservices.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "test-data/app-config.json").AsConfig | indent 2 }}
---

