apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservices.fullname" . }}-web-ui-config
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "microservices.labels" . | nindent 4 }}
data:
  app-config.json: |-
{{ .Files.Get "test-data/app-config.json" | indent 4 }}
