apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-profile-service
  labels:
    {{- include "microservices.labels" . | nindent 4 }}.profile-service
spec:
  type: ClusterIP
  ports:
    - port: 28080
      targetPort: 28080
      protocol: TCP
  selector:
    app: {{ include "microservices.fullname" . }}.profile-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-recipes-service
  labels:
    {{- include "microservices.labels" . | nindent 4 }}.recipes-service
spec:
  type: ClusterIP
  ports:
    - port: 28080
      targetPort: 28080
      protocol: TCP
  selector:
    app: {{ include "microservices.fullname" . }}.recipes-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-ingredients-service
  labels:
    {{- include "microservices.labels" . | nindent 4 }}.ingredients-service
spec:
  type: ClusterIP
  ports:
    - port: 28080
      targetPort: 28080
      protocol: TCP
  selector:
    app: {{ include "microservices.fullname" . }}.ingredients-service

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-lists-service
  labels:
    {{- include "microservices.labels" . | nindent 4 }}.lists-service
spec:
  type: ClusterIP
  ports:
    - port: 28080
      targetPort: 28080
      protocol: TCP
  selector:
    app: {{ include "microservices.fullname" . }}.lists-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-web-ui
  labels:
    {{- include "microservices.labels" . | nindent 4 }}.web-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "microservices.fullname" . }}.web-ui
