apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices.fullname" . }}.web-ui
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
    {{- include "microservices.labels" . | nindent 4 }}.web-ui    
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "microservices.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "microservices.fullname" . }}.web-ui
        {{- include "microservices.selectorLabels" . | nindent 8 }}       
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "microservices.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}     
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}web-ui:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST
              value: "{{ .Release.Name }}-kafka"
            - name: THORNTAIL_KAFKA_DASH_CONFIGURATION_POST
              value: "9092"
            - name: THORNTAIL_PORT_OFFSET
              value: "0"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
#           livenessProbe:
#             httpGet:
#               path: /instrument
#               port: http
#             initialDelaySeconds: 60
#             periodSeconds: 20                            
#           readinessProbe:
#             httpGet:
#               path: /instrument
#               port: http
#             initialDelaySeconds: 60
#             periodSeconds: 20                                                 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}